[package]
name = "client-cli"
version = "0.1.0"
authors = ["Artem Yarulin <artem.yarulin@kapteko.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
